const tours = [
	{
        id: 0,
        name: '6 Days Luxury Western Corridor Migration',
        tags: ['Safari', 'Top Rated'],
        parks: 'Tarangire, Western Serengeti, Ngorongoro Crater & Lake Manyara',
    },
    {
        id: 1,
        name: '7 Days Luxury North Migration Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti & Ngorongoro Crater',
    },
    {
        id: 2,
        name: '6 Days Luxury Tanzania Safari Calving Season',
        tags: ['Safari'],
        parks: 'Tarangire, South Serengeti, Ngorongoro Crater & Lake Manyara',
    },
    {
        id: 3,
        name: '6 Days Midrange Western Corridor Migration',
        tags: ['Safari'],
        parks: 'Tarangire, Western Serengeti, Ngorongoro Crater & Lake Manyara',
    },
    {
        id: 4,
        name: '6 Days Midrange Tanzania Safari Calving Season',
        tags: ['Safari'],
        parks: 'Tarangire, South Serengeti, Ngorongoro Crater & Lake Manyara',
    },
    {
        id: 5,
        name: '8 Days Luxury North Migration Safari',
        tags: ['Safari', 'Top Rated'],
        parks: 'Tarangire, Serengeti, Manyara & Ngorongoro Crater',
    },
    {
        id: 6,
        name: '7 Days Midrange North Migration Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti & Ngorongoro Crater',
    },
    {
        id: 7,
        name: '8 Days Midrange North Migration Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti, Manyara & Ngorongoro Crater',
    },
    {
        id: 8,
        name: '8 Days Luxury Family Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti, Manyara & Ngorongoro Crater',
    },
    {
        id: 9,
        name: '12 Days Luxury Honeymoon Safari + Beach',
        tags: ['Safari', 'Zanzibar'],
        parks: 'Tarangire, Serengeti, Manyara, Ngorongoro Crater & Zanzibar',
    },
    {
        id: 10,
        name: '9 Days Midrange Honeymoon Tanzania Safari',
        tags: ['Safari', 'Honeymoon', 'Zanzibar', 'Top Rated'],
        parks: 'Tarangire, Serengeti, Ngorongoro Crater & Zanzibar',
    },
    {
        id: 11,
        name: '9 Days Midrange Family Tanzania Safari',
        tags: ['Safari', 'Zanzibar'],
        parks: 'Tarangire, Serengeti, Ngorongoro Crater & Zanzibar',
    },
    {
        id: 12,
        name: 'Ngorongoro Crater Day Trip',
        tags: ['Safari', 'Day Trip'],
        parks: 'Ngorongoro Crater',
    },
    {
        id: 13,
        name: 'Tarangire National Park Day Trip',
        tags: ['Safari', 'Day Trip'],
        parks: 'Tarangire National Park',
    },
    {
        id: 14,
        name: 'Lake Manyara National Park Day Trip',
        tags: ['Safari', 'Day Trip'],
        parks: 'Lake Manyara National Park',
    },
    {
        id: 15,
        name: '7 Days Luxury Tanzania Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti, Ngorongoro Crater & Lake Manyara',
    },
    {
        id: 16,
        name: '7 Days Camping Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Ngorongoro Crater, Serengeti & Lake Manyara',
    },
    {
        id: 17,
        name: '7 Days Midrange Tanzania Safari',
        tags: ['Safari'],
        parks: 'Tarangire, Serengeti, Ngorongoro Crater & Lake Manyara',
    },
];
export default tours;
