graph LR
    A((Oak))
    A --> B["👋 Landing Page"]
    A --> C["💲 Pricing Page"]:::taskForNazif
    A --> D["✍️ Login/Register Page"]
    D --> E["📧 Email Authentication"]
    A --> F["📱 User-side App"]
    F --> G["💼 Contract Management"]
    G --> H["🗃️ Contract repository"]:::taskForNazif
    H --> I["📑 Contract table"]:::taskForNazif
    H --> J["🔍 Search & Filter by XYZ"]
    G --> K["📝 Contract entry form"]
    G --> L["📊 Contract report"]
    F --> M["📝 Bill management"]
    F --> N["📩 Notifications"]
    N --> O["📋 Pending contract approvals"]
    N --> P["📋 Pending bill approvals"]
    N --> Q["📋 Pending contract reviews"]
    N --> R["📋 Requested admin help"]
    F --> S["⚙️ Account settings"]
    S --> T["📝 Edit profile"]
    S --> U["📝 Edit notification settings"]
    S --> V["📝 Edit approval settings"]
    F --> W["⚙️ Company settings admin only"]
    W --> X["📝 Edit user accounts"]
    X --> Y["📝 Edit permissions"]
    X --> Z["📝 Edit approvers"]
    X --> AA["📝 Edit approval thresholds"]
    W --> AB["📝 Edit company billing settings"]
    F --> AC["💰 Payment"]
    AC --> AD["🔄 Select Payment cycle"]
    AC --> AE["💳 Go to Stripe checkout"]
    F --> AF["⏳ Company Logs"]
    AF --> AG["🗃️ Contract logs"]
    AG --> AH["➕ Contract created"]
    AH --> AI["⏰ date-time of event, 📜 Entire contract item"]
    AG --> AJ["🔄 Contract modified"]
    AJ --> AK["⏰ date-time of event, 🆔 ID, fields modified, old value & new value for each."]
    AG --> AL["🗑️ Contract deleted"]
    AL --> AM["⏰ date-time of event, 📜 Entire contract item"]
    AF --> AN["🗃️ Bill logs"]
    AF --> AO["🗃️ User logs"]
    AO --> AP["➕ User created"]
    AP --> AQ["⏰ date-time of event, 📜 Entire user item"]
    AO --> AR["📲 User login"]
    AR --> AS["⏰ date-time of event, 🆔 User ID"]
    AO --> AT["🚪 User logout"]
    AT --> AU["⏰ date-time of event, 🆔 User ID"]
    AO --> AV["🗑️ User deleted"]
    AV --> AW["⏰ date-time of event, 📜 Entire user item"]
    AO --> AX["🔄 User modified"]
    AX --> AY["⏰ date-time of event, 🆔 ID, fields modified, old value & new value for each."]
    AF --> AZ["🗃️ Payment logs"]
    AZ --> BA["💸 Item paid, billing modified, refund requested, refund approved, refund denied"]
    A --> BB["Vendor-side App"]
    BB --> BC["Post MVP"]


    classDef taskForNazif fill:#559999